### ISSUE TITLE
Fix up glide.yaml to flatten dependecies

### ISSUE THREAD

**Issue by rthallisey** [fusor/ansible-service-broker#100]
As part of make build we remove docker vendor dependency instead of having glide flatten it ```rm -rf ${GOPATH}/src/github.com/fusor/ansible-service-broker/vendor/github.com/docker/docker/vendor```.  We should get glide.yaml & glide.lock into good shape so we don't have to do this anymore and it avoid this coming up in the future.

**Comment by jmrodri** [comment]
I tried using `glide --strip-vendor ...` but hit another weird issue. I then gave up.

**Comment by rthallisey** [comment]
@jmrodri I think we should keep this open for at least one more patch. I wrote a TODO list for this somewhere, but I think I've lost it....

Here are some additions we need to complete this:
- Change ```glide install``` to ```glide install -v``` everywhere and test!
- Update the docs to reflect that change
- Remove this line from the Makefile: ```rm -rf ${GOPATH}/src/github.com/fusor/ansible-service-broker/vendor/github.com/docker/docker/vendor```

**Comment by jmrodri** [comment]
@rthallisey I made both the `glide install -v` change and removed the `rm -rf`. This causes a failure:

```
$ make install                                                     
go install -ldflags="-s -w" ./cmd/broker                                                                         
# github.com/fusor/ansible-service-broker/vendor/github.com/docker/distribution/context                          
vendor/github.com/docker/distribution/context/logger.go:104: undefined: logrus.StandardLogger                    
Makefile:8: recipe for target 'install' failed                                                                   
make: *** [install] Error 2                                                                                      
```
I guess this means we need to add that to our `glide.yaml`?

**Comment by rthallisey** [comment]
@jmrodri The logrus pkg should be in glide.yaml.
```
- package: github.com/Sirupsen/logrus
  version: v0.11.4
```

Maybe try clearing the glide cache and install the deps again? ```rm -rf ~/.glide``` and ```rm -rf $GOPATH/src/github.com/fusor/ansible-service-broker/vendor/```.

**Comment by rthallisey** [comment]
I cleared my cache and I'm seeing the issue.

**Comment by rthallisey** [comment]
@jmrodri The issue is the glide.lock file is out of date. Maybe we shouldn't carry a glide.lock file? For now, I'll update it.
